### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by mipastgt** [Ashampoo/kim#48]
KIM cannot extract image size from WEBP images. The following test fragment fails for the attached test image.

```
val metadata = Kim.readMetadata(encodedBytes)
assertNotNull(metadata)
assertNotNull(metadata.imageSize)
```
[skia-generated-test-image.webp.zip](https://github.com/Ashampoo/kim/files/13716288/skia-generated-test-image.webp.zip)

**Comment by StefanOltmann** [comment]
Thank you for reaching out. Currently, we do not have support for WebP at all.

When we initially forked the Apache Commons Imaging project, WebP support was not included. However, there is now a merged pull request that addresses this limitation (https://github.com/apache/commons-imaging/pull/254), making WebP support possible.

While WebP support is not in high demand based on our current user surveys for Ashampoo Photos, we are open to implementing it if users express a need for this feature.

Alternatively, we welcome contributions from the community. If you are interested in becoming a contributor, please feel free to submit a pull request. We appreciate your interest and support! 🙂

**Comment by StefanOltmann** [comment]
@mipastgt Because of the reasons I stated above I couldn't justify spending company time on WebP support, so today I implemented it in my free time for the fun of it. :) 

My aim and personal wish is to ensure that this library becomes as useful and comprehensive as possible.

I ping you again as soon as it's available on Maven Central.

**Comment by StefanOltmann** [comment]
@mipastgt It's available now. Give it a try and let me know if you encounter any issues. :)
